/*
 * Customer Portal API
 *
 * An example customer portal OpenAPI specification
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the CameraAPI part of the API
	CameraAPI CameraAPI
	// Routes for the SubscriberAPI part of the API
	SubscriberAPI SubscriberAPI
	// Routes for the SubscriptionAPI part of the API
	SubscriptionAPI SubscriptionAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"AddCamera",
			http.MethodPost,
			"/camera",
			handleFunctions.CameraAPI.AddCamera,
		},
		{
			"GetCamera",
			http.MethodGet,
			"/camera",
			handleFunctions.CameraAPI.GetCamera,
		},
		{
			"UpdateCamera",
			http.MethodPut,
			"/camera/:cameraId",
			handleFunctions.CameraAPI.UpdateCamera,
		},
		{
			"UpdateCameraLocation",
			http.MethodPut,
			"/camera/:cameraId/location",
			handleFunctions.CameraAPI.UpdateCameraLocation,
		},
		{
			"AddSubscriber",
			http.MethodPost,
			"/subscribers",
			handleFunctions.SubscriberAPI.AddSubscriber,
		},
		{
			"DeleteSubscriber",
			http.MethodDelete,
			"/subscriber/:subscriberId",
			handleFunctions.SubscriberAPI.DeleteSubscriber,
		},
		{
			"GetSubscriberById",
			http.MethodGet,
			"/subscriber/:subscriberId",
			handleFunctions.SubscriberAPI.GetSubscriberById,
		},
		{
			"GetSubscribers",
			http.MethodGet,
			"/subscribers",
			handleFunctions.SubscriberAPI.GetSubscribers,
		},
		{
			"GetSubscribersSubscriptions",
			http.MethodGet,
			"/subscriber/:subscriberId/subscription",
			handleFunctions.SubscriberAPI.GetSubscribersSubscriptions,
		},
		{
			"UpdateSubscriber",
			http.MethodPut,
			"/subscriber/:subscriberId",
			handleFunctions.SubscriberAPI.UpdateSubscriber,
		},
		{
			"AddSubscription",
			http.MethodPost,
			"/subscription",
			handleFunctions.SubscriptionAPI.AddSubscription,
		},
		{
			"DeleteSubscription",
			http.MethodDelete,
			"/subscription/:subscriptionId",
			handleFunctions.SubscriptionAPI.DeleteSubscription,
		},
		{
			"GetSubscribersCamera",
			http.MethodGet,
			"/subscription/:subscriptionId/camera",
			handleFunctions.SubscriptionAPI.GetSubscribersCamera,
		},
		{
			"GetSubscription",
			http.MethodGet,
			"/subscription",
			handleFunctions.SubscriptionAPI.GetSubscription,
		},
		{
			"GetSubscriptionById",
			http.MethodGet,
			"/subscription/:subscriptionId",
			handleFunctions.SubscriptionAPI.GetSubscriptionById,
		},
		{
			"UpdateSubscription",
			http.MethodPut,
			"/subscription/:subscriptionId",
			handleFunctions.SubscriptionAPI.UpdateSubscription,
		},
	}
}
