services:
  customer-portal:
    container_name: portal
    build:
      context: ./out/gin
    network_mode: host
    image: gin-portal
    expose:
      - "8080"
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - customer-portal
