// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: api/subscription-service/subscription-service.proto

package subscription_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveStreamAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberId int32 `protobuf:"varint,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	RobotId      int32 `protobuf:"varint,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	CameraId     int32 `protobuf:"varint,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
}

func (x *LiveStreamAccessRequest) Reset() {
	*x = LiveStreamAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subscription_service_subscription_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveStreamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStreamAccessRequest) ProtoMessage() {}

func (x *LiveStreamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_service_subscription_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStreamAccessRequest.ProtoReflect.Descriptor instead.
func (*LiveStreamAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_service_subscription_service_proto_rawDescGZIP(), []int{0}
}

func (x *LiveStreamAccessRequest) GetSubscriberId() int32 {
	if x != nil {
		return x.SubscriberId
	}
	return 0
}

func (x *LiveStreamAccessRequest) GetRobotId() int32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *LiveStreamAccessRequest) GetCameraId() int32 {
	if x != nil {
		return x.CameraId
	}
	return 0
}

type LiveStreamAccessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberId int32 `protobuf:"varint,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	RobotId      int32 `protobuf:"varint,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	CameraId     int32 `protobuf:"varint,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	IsAllowed    bool  `protobuf:"varint,4,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
}

func (x *LiveStreamAccessReply) Reset() {
	*x = LiveStreamAccessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subscription_service_subscription_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveStreamAccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveStreamAccessReply) ProtoMessage() {}

func (x *LiveStreamAccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_service_subscription_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveStreamAccessReply.ProtoReflect.Descriptor instead.
func (*LiveStreamAccessReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_service_subscription_service_proto_rawDescGZIP(), []int{1}
}

func (x *LiveStreamAccessReply) GetSubscriberId() int32 {
	if x != nil {
		return x.SubscriberId
	}
	return 0
}

func (x *LiveStreamAccessReply) GetRobotId() int32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *LiveStreamAccessReply) GetCameraId() int32 {
	if x != nil {
		return x.CameraId
	}
	return 0
}

func (x *LiveStreamAccessReply) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

type ControlAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberId int32 `protobuf:"varint,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	RobotId      int32 `protobuf:"varint,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	ActuatorId   int32 `protobuf:"varint,3,opt,name=actuator_id,json=actuatorId,proto3" json:"actuator_id,omitempty"`
}

func (x *ControlAccessRequest) Reset() {
	*x = ControlAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subscription_service_subscription_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAccessRequest) ProtoMessage() {}

func (x *ControlAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_service_subscription_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAccessRequest.ProtoReflect.Descriptor instead.
func (*ControlAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_subscription_service_subscription_service_proto_rawDescGZIP(), []int{2}
}

func (x *ControlAccessRequest) GetSubscriberId() int32 {
	if x != nil {
		return x.SubscriberId
	}
	return 0
}

func (x *ControlAccessRequest) GetRobotId() int32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *ControlAccessRequest) GetActuatorId() int32 {
	if x != nil {
		return x.ActuatorId
	}
	return 0
}

type ControlAccessReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriberId int32 `protobuf:"varint,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	RobotId      int32 `protobuf:"varint,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	ActuatorId   int32 `protobuf:"varint,3,opt,name=actuator_id,json=actuatorId,proto3" json:"actuator_id,omitempty"`
	IsAllowed    bool  `protobuf:"varint,4,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
}

func (x *ControlAccessReply) Reset() {
	*x = ControlAccessReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_subscription_service_subscription_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlAccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlAccessReply) ProtoMessage() {}

func (x *ControlAccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscription_service_subscription_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlAccessReply.ProtoReflect.Descriptor instead.
func (*ControlAccessReply) Descriptor() ([]byte, []int) {
	return file_api_subscription_service_subscription_service_proto_rawDescGZIP(), []int{3}
}

func (x *ControlAccessReply) GetSubscriberId() int32 {
	if x != nil {
		return x.SubscriberId
	}
	return 0
}

func (x *ControlAccessReply) GetRobotId() int32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *ControlAccessReply) GetActuatorId() int32 {
	if x != nil {
		return x.ActuatorId
	}
	return 0
}

func (x *ControlAccessReply) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

var File_api_subscription_service_subscription_service_proto protoreflect.FileDescriptor

var file_api_subscription_service_subscription_service_proto_rawDesc = []byte{
	0x0a, 0x33, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x17, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x22, 0x93, 0x01,
	0x0a, 0x15, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x22, 0x77, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x61, 0x63, 0x74, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a,
	0x12, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x75, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x75, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x32, 0x9c, 0x01, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x4c,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x76, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x15, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x41, 0x6e, 0x74, 0x6f, 0x6e, 0x2d, 0x41, 0x75, 0x67, 0x75, 0x73, 0x74, 0x73, 0x73, 0x6f,
	0x6e, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2d, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_subscription_service_subscription_service_proto_rawDescOnce sync.Once
	file_api_subscription_service_subscription_service_proto_rawDescData = file_api_subscription_service_subscription_service_proto_rawDesc
)

func file_api_subscription_service_subscription_service_proto_rawDescGZIP() []byte {
	file_api_subscription_service_subscription_service_proto_rawDescOnce.Do(func() {
		file_api_subscription_service_subscription_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_subscription_service_subscription_service_proto_rawDescData)
	})
	return file_api_subscription_service_subscription_service_proto_rawDescData
}

var file_api_subscription_service_subscription_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_subscription_service_subscription_service_proto_goTypes = []interface{}{
	(*LiveStreamAccessRequest)(nil), // 0: LiveStreamAccessRequest
	(*LiveStreamAccessReply)(nil),   // 1: LiveStreamAccessReply
	(*ControlAccessRequest)(nil),    // 2: ControlAccessRequest
	(*ControlAccessReply)(nil),      // 3: ControlAccessReply
}
var file_api_subscription_service_subscription_service_proto_depIdxs = []int32{
	0, // 0: SubscriptionService.LiveStreamAccess:input_type -> LiveStreamAccessRequest
	2, // 1: SubscriptionService.ControlAccess:input_type -> ControlAccessRequest
	1, // 2: SubscriptionService.LiveStreamAccess:output_type -> LiveStreamAccessReply
	3, // 3: SubscriptionService.ControlAccess:output_type -> ControlAccessReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_subscription_service_subscription_service_proto_init() }
func file_api_subscription_service_subscription_service_proto_init() {
	if File_api_subscription_service_subscription_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_subscription_service_subscription_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveStreamAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_subscription_service_subscription_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveStreamAccessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_subscription_service_subscription_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_subscription_service_subscription_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlAccessReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_subscription_service_subscription_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_subscription_service_subscription_service_proto_goTypes,
		DependencyIndexes: file_api_subscription_service_subscription_service_proto_depIdxs,
		MessageInfos:      file_api_subscription_service_subscription_service_proto_msgTypes,
	}.Build()
	File_api_subscription_service_subscription_service_proto = out.File
	file_api_subscription_service_subscription_service_proto_rawDesc = nil
	file_api_subscription_service_subscription_service_proto_goTypes = nil
	file_api_subscription_service_subscription_service_proto_depIdxs = nil
}
