// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: api/subscription-service/subscription-service.proto

package subscription_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	LiveStreamAccess(ctx context.Context, in *LiveStreamAccessRequest, opts ...grpc.CallOption) (*LiveStreamAccessReply, error)
	ControlAccess(ctx context.Context, in *ControlAccessRequest, opts ...grpc.CallOption) (*ControlAccessReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) LiveStreamAccess(ctx context.Context, in *LiveStreamAccessRequest, opts ...grpc.CallOption) (*LiveStreamAccessReply, error) {
	out := new(LiveStreamAccessReply)
	err := c.cc.Invoke(ctx, "/Greeter/LiveStreamAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ControlAccess(ctx context.Context, in *ControlAccessRequest, opts ...grpc.CallOption) (*ControlAccessReply, error) {
	out := new(ControlAccessReply)
	err := c.cc.Invoke(ctx, "/Greeter/ControlAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	LiveStreamAccess(context.Context, *LiveStreamAccessRequest) (*LiveStreamAccessReply, error)
	ControlAccess(context.Context, *ControlAccessRequest) (*ControlAccessReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) LiveStreamAccess(context.Context, *LiveStreamAccessRequest) (*LiveStreamAccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiveStreamAccess not implemented")
}
func (UnimplementedGreeterServer) ControlAccess(context.Context, *ControlAccessRequest) (*ControlAccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlAccess not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_LiveStreamAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveStreamAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).LiveStreamAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/LiveStreamAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).LiveStreamAccess(ctx, req.(*LiveStreamAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ControlAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ControlAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/ControlAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ControlAccess(ctx, req.(*ControlAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LiveStreamAccess",
			Handler:    _Greeter_LiveStreamAccess_Handler,
		},
		{
			MethodName: "ControlAccess",
			Handler:    _Greeter_ControlAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/subscription-service/subscription-service.proto",
}
