// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: api/subscription-service/subscription-service.proto

package subscription_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	LiveStreamAccess(ctx context.Context, in *LiveStreamAccessRequest, opts ...grpc.CallOption) (*LiveStreamAccessReply, error)
	ControlAccess(ctx context.Context, in *ControlAccessRequest, opts ...grpc.CallOption) (*ControlAccessReply, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) LiveStreamAccess(ctx context.Context, in *LiveStreamAccessRequest, opts ...grpc.CallOption) (*LiveStreamAccessReply, error) {
	out := new(LiveStreamAccessReply)
	err := c.cc.Invoke(ctx, "/SubscriptionService/LiveStreamAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionServiceClient) ControlAccess(ctx context.Context, in *ControlAccessRequest, opts ...grpc.CallOption) (*ControlAccessReply, error) {
	out := new(ControlAccessReply)
	err := c.cc.Invoke(ctx, "/SubscriptionService/ControlAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	LiveStreamAccess(context.Context, *LiveStreamAccessRequest) (*LiveStreamAccessReply, error)
	ControlAccess(context.Context, *ControlAccessRequest) (*ControlAccessReply, error)
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) LiveStreamAccess(context.Context, *LiveStreamAccessRequest) (*LiveStreamAccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiveStreamAccess not implemented")
}
func (UnimplementedSubscriptionServiceServer) ControlAccess(context.Context, *ControlAccessRequest) (*ControlAccessReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlAccess not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_LiveStreamAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveStreamAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).LiveStreamAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SubscriptionService/LiveStreamAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).LiveStreamAccess(ctx, req.(*LiveStreamAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionService_ControlAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServiceServer).ControlAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SubscriptionService/ControlAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServiceServer).ControlAccess(ctx, req.(*ControlAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LiveStreamAccess",
			Handler:    _SubscriptionService_LiveStreamAccess_Handler,
		},
		{
			MethodName: "ControlAccess",
			Handler:    _SubscriptionService_ControlAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/subscription-service/subscription-service.proto",
}
