apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-remote-controller-deployment
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: robot-remote-controller
  template:
    metadata:
      labels:
        app: robot-remote-controller
    spec:
      containers:
      - name: robot-remote-controller
        image: robot-remote-controller-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
