apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deployment
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
      - name: subscription
        image: subscription-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
