apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal-deployment
spec:
  replicas: 1 # Adjust replica count as needed
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: customer-portal
        image: customer-portal:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        hostPath:
          path: ./nginx.conf # Adjust the host path to the nginx.conf file
          type: File
